before_install:
- source .travis-env-vars.sh
- nvm install
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.2
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add @ionic/cli@6.8.0 @angular/cli@9.1.3 cordova@9.0.0
- git config --local user.name "travis"
- git config --local user.email "travis@yopmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
matrix:
  include:
  - os: linux
    sudo: false
    language: node_js
    cache: yarn
    script:
    - yarn --version
    - yarn
    - ionic build --configuration=$PROFILE
    before_deploy:
    - git tag $TRAVIS_TAG
    - rm -f dist/yoga-booking-app-$PROFILE.tar.gz
    - mkdir -p dist
    - tar czf dist/yoga-booking-app-$PROFILE.tar.gz www
    deploy:
      provider: releases
      api_key: "$GITHUB_API_TOKEN"
      name: "WebApp - $PROFILE ($TRAVIS_BRANCH $DATE_TIME)"
      file:
      - dist/yoga-booking-app-$PROFILE.tar.gz
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        all_branches: true
        repo: aurelien-baudet/yoga-classes-booking-ui
  - os: linux
    sudo: false
    language: android
    android:
      components:
      - tools
      - platform-tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_VERSION
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - "$HOME/.gradle/caches/"
      - "$HOME/.gradle/wrapper/"
      - "$HOME/.android/build-cache"
    before_script:
    - openssl aes-256-cbc -K $secrets_key -iv $secrets_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xf secrets.tar
    script:
    - yarn --version
    - yarn
    - ionic cordova build android  --configuration=$PROFILE --release
    - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore $keystore -storepass
      $storepass -keypass $keypass platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      $alias
    - "$ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS_VERSION/zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
      platforms/android/app/build/outputs/apk/release/app-release-signed.apk"
    before_deploy:
    - git tag $TRAVIS_TAG
    - rm -f dist/yoga-booking-release-$PROFILE.apk
    - mkdir -p dist
    - cp platforms/android/app/build/outputs/apk/release/app-release-signed.apk dist/yoga-booking-release-$PROFILE.apk
    deploy:
      provider: releases
      api_key: "$GITHUB_API_TOKEN"
      name: "Android - $PROFILE ($TRAVIS_BRANCH $DATE_TIME)"
      file:
      - dist/yoga-booking-release-$PROFILE.apk
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        all_branches: true
        repo: aurelien-baudet/yoga-classes-booking-ui
