
before_install:
- nvm install
- export PATH="$(yarn global bin):$PATH"
- yarn global add ionic@5.2.8 cordova@9.0.0

matrix:
  include:
  # build web app
  - os: linux
    sudo: false
    language: node_js
    cache: yarn
    script:
    - yarn install
    - ionic build --prod
    before_deploy:
    - rm -f dist/yoga-booking-app.tar.gz
    - mkdir -p dist
    - tar czf dist/yoga-booking-app.tar.gz www
    deploy:
      provider: releases
      api_key:
        secure: $GITHUB_API_TOKEN
      file:
        - dist/yoga-booking-app.tar.gz
      skip_cleanup: true
      draft: true
      on:
        repo: aurelien-baudet/yoga-classes-booking-ui
  # build Android app
  - os: linux
    sudo: false
    language: android
    addons:
      apt:
        sources:
        - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
          key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
        packages:
        - yarn
    android:
      components:
      - tools
      - platform-tools
      - build-tools-$ANDROID_BUILD_TOOLS
      - android-$ANDROID_API
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
    licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    before_cache:
    - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
    - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
      - $HOME/.gradle/caches/
      - $HOME/.gradle/wrapper/
      - $HOME/.android/build-cache
    before_script:
    - openssl aes-256-cbc -K $encrypted_f3734ef198a2_key -iv $encrypted_f3734ef198a2_iv -in secrets.tar.enc -out secrets.tar -d
    - tar xf secrets.tar
    script:
    - yarn install
    - ionic cordova build android --prod --release
    - jarsigner -verbose -sigalg SHA1withRSA -digestalg SHA1 -keystore debug.keystore -storepass $storepass -keypass $keypass platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk debug
    - $ANDROID_HOME/build-tools/$ANDROID_BUILD_TOOLS/zipalign -v 4 platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk platforms/android/app/build/outputs/apk/release/app-release-signed.apk
    before_deploy:
    - rm -f dist/yoga-booking-release.apk
    - mkdir -p dist
    - cp platforms/android/app/build/outputs/apk/release/app-release-signed.apk dist/yoga-booking-release.apk
    deploy:
      provider: releases
      api_key:
        secure: $GITHUB_API_TOKEN
      file:
        - dist/yoga-booking-release.apk
      skip_cleanup: true
      draft: true
      on:
        repo: aurelien-baudet/yoga-classes-booking-ui
  # build iOS app
  # - os: osx
  #   language: objective-c
  #   osx_image: xcode8.3
    # addons:
    #   apt:
    #     sources:
    #     - sourceline: deb https://dl.yarnpkg.com/debian/ stable main
    #       key_url: https://dl.yarnpkg.com/debian/pubkey.gpg
    #     packages:
    #     - oracle-java8-installer
    #     - oracle-java8-set-default
    #     - yarn
    #     - jq
  #   before_install:
  #   - export LANG=en_US.UTF-8
  #   - brew update ; brew install yarn ios-sim
  #     jq ios-deploy cocoapods ; rvm use system ; pod setup
  #   before_script:
  #   - ./travis/addkeys.sh    
  #   script:
  #   - ./travis/build-ios.sh
  #   - ./travis/package-ios.sh
  # deploy:
#   provider: releases
#   api_key:
#     secure: $GITHUB_API_TOKEN
#   file:
#     - dist/yoga-booking-release-unsigned.app.tgz
#   skip_cleanup: true
#   draft: true
#   on:
#     repo: aurelien-baudet/yoga-classes-booking-ui

